config/routes.rb
Homework1::Application.routes.draw do
  resources :portfolios

  get "pages/index"
  devise_for :members
  resources :investments
  resources :stocks
  resources :members, only: [:show, :index]
  resources :posts
  resources :pages
  
  get "refresh_stocks", to: "stocks#refresh_stocks"
  get "increment_stock/:id/:i_id", to: "stocks#increment_stock", as: "increment_stock"
  get "deincrement_stock/:id/:i_id", to: "stocks#deincrement_stock", as: "deincrement_stock"
  get "delete_stock_investments/:id", to: "investments#delete_stock_investments", as: "delete_stock_investments"
  get "order/:dollar/:decimal", to: "portfolios#order", as: "order"
  
  root 'home#index'
  

end

app/models/investment.rb
class Investment < ActiveRecord::Base
  belongs_to :stock
  belongs_to :member

  validates :stock, presence: true
  validates :member, presence: true
  validates :share_change, presence: true
  validate :share_change_not_zero

  def share_change_not_zero
  	errors.add(:base, "Cannot purchase zero shares!") if (share_change == 0)
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_filter :authenticate_member!
  before_action :set_investment, only: [:show, :edit, :update, :destroy]
  include StocksHelper

  # GET /investments
  # GET /investments.json
  def index
    if member_signed_in? 
      @investments = Investment.all
    else
      @investments = []
    end  
  end

  # GET /investments/1
  # GET /investments/1.json
  def show
  end

  # GET /investments/new
  def new
    @investment = Investment.new
    @stocks = Stock.all
  end   

  # GET /investments/1/edit
  def edit
    @investment = Investment.find(params[:id])
  end

  # POST /investments
  # POST /investments.json
  def create
    @stocks = Stock.all
    if member_signed_in? 
      @investment = Investment.new(investment_params)
    
      if @investment.save
        @stock_id = @investment.stock_id
        @stock = Stock.where(id: @stock_id).first
        negate = BigDecimal("-1")
        price = StockQuote::Stock.quote(@stock.ticker).last_trade_price_only
        value = BigDecimal(@investment.share_change.to_s) * negate * price
        Rails.logger.debug("investments deebug: " + value.to_s)
        redirect_to order_path(value.truncate.to_s, value.abs().frac().to_s[2..-1])
      else
        respond_to do |format|
          format.html { render action: 'new' }
          format.json { render json: @investment.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_member_session_path
    end
  end

  # PATCH/PUT /investments/1
  # PATCH/PUT /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1
  # DELETE /investments/1.json
  def destroy
    @stock_id = @investment.stock_id
    @stock = Stock.where(id: @stock_id).first
    price = StockQuote::Stock.quote(@stock.ticker).last_trade_price_only
    value = BigDecimal(@investment.share_change.to_s) * price
    @investment.destroy
    redirect_to order_path(value.round.to_s, value.abs().frac().to_s[2..-1])
  end

  def delete_member_investments
    @investments = Investment.where("member_id = ?", params[:id])
    @investments.each  do |x|
      x.destroy
    end 
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def delete_stock_investments
    @investments = Investment.where("stock_id = ?", params[:id])
    @investments.each  do |x|
      x.destroy
    end  
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully deleted.' }
      format.json { head :no_content }
    end  
  end    

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = Investment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investment_params
      params.fetch(:investment,{}).permit(:member_id, :stock_id, :share_change)
    end
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/_form.html.erb
<%= form_for(@investment) do |f| %>
  <% if @investment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
      <% @investment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>member</p>
    <%= f.collection_select :member_id, Member.all, :id, :name%>
  </div>
  <div class="field">
    <p>stock</p>
    <%= f.collection_select :stock_id, Stock.all, :id, :name%>
  </div>
  <div class="field">
    <%= f.label :share_change %><br>
    <%= f.number_field :share_change %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investments/index.html.erb
<center>
<div class="content_box">
<h1>Investment List</h1>
<table>
  <thead>
    <tr>
      <th>Member&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>Stock&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>Share Change&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @investments.each do |investment| %>
      <tr>
        <td><%= investment.member.name %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= investment.stock.name %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= investment.share_change %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investment', new_investment_path %>
</div>
</div>
</center>

app/views/investments/new.html.erb
<center>
<%= stylesheet_link_tag "investment" %>

<h1>Make a New Investment</h1>

<%= form_for(@investment) do |f| %>
	<div class="field">
    <p>Stock</p>
    <%= f.collection_select :stock_id, Stock.all, :id, :name %>
  </div>
  <div class="field"S>
    <%= f.label :share_change %><br>
    <%= f.number_field :share_change %>
  </div>
  <div class="field">
    <%= f.hidden_field :member_id, :value => current_member.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div class="error-msg"> 
    <% if @investment.errors.any? %> 
    <ul> 
      <% @investment.errors.full_messages.each do |msg| %> 
      <li><%= msg %></li> 
      <% end %> 
    </ul> 
    <% end %> 
  </div>
  <br>
  <button class= "hide-btn3" type="button"> 
    Hide stock quotes
  </button>
  <div class="dash-review5">
    <h3><strong>Quotes:</strong></h3>
    <% @stocks.each do |stock| %>
      <p><%= link_to stock.name, stock_path(stock.id) %>: <%= stock.price %></p>
    <% end %> 
  </div> 
<% end %> 
</center>

app/views/investments/show.html.erb
<div class="content_box">
<center>
<p id="notice"><%= notice %></p>

<p>
  <strong>Member:</strong>
  <%= @investment.member.name %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @investment.stock.name %>
</p>

<p>
  <strong>Share change:</strong>
  <%= @investment.share_change %>
</p>

<%= link_to 'Edit', edit_investment_path(@investment) %> |
<%= link_to 'Back', investments_path %>
</center>
</div>