config/routes.rb
Homework1::Application.routes.draw do
  resources :portfolios

  get "pages/index"
  devise_for :members
  resources :investments
  resources :stocks
  resources :members, only: [:show, :index]
  resources :posts
  resources :pages
  
  get "refresh_stocks", to: "stocks#refresh_stocks"
  get "increment_stock/:id/:i_id", to: "stocks#increment_stock", as: "increment_stock"
  get "deincrement_stock/:id/:i_id", to: "stocks#deincrement_stock", as: "deincrement_stock"
  get "delete_stock_investments/:id", to: "investments#delete_stock_investments", as: "delete_stock_investments"
  get "order/:dollar/:decimal", to: "portfolios#order", as: "order"
  
  root 'home#index'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :member

  validates :body, length: {maximum: 200}, presence: true 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_member!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    if member_signed_in? 
      @posts = Post.all
    else
      @posts = []
    end  
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    if member_signed_in?
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render action: 'show', stat: :created, location: @post }
        else
          format.html { render action: 'new' }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end      
    else
      redirect_to new_member_session_path
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post,{}).permit(:title, :body, :text, :member_id, :stock_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<center>
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  </div>
  <div class="field">
    <p>stock</p>
    <%= f.collection_select :stock_id, Stock.all, :id, :name%>
  </div>
  <div class="field">
    <p>member</p>
    <%= f.collection_select :member_id, Member.all, :id, :name%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</center>

app/views/posts/edit.html.erb
<center>
<h1>Editing post</h1>

<div class="error-msg"> 
		<% if @post.errors.any? %> 
		<ul> 
			<% @post.errors.full_messages.each do |msg| %> 
			<li><%= msg %></li> 
 			<% end %> 
 		</ul> 
		<% end %> 
</div>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</center>

app/views/posts/index.html.erb
<center>
<div class="content-box">  
<h1>Announcements</h1>

<table>
  <thead>
    <tr>
      <th>Title&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>Body&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>Member&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= post.body %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= post.member.name %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= link_to 'Show', post %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= link_to 'Edit', edit_post_path(post) %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p></p>
<%= link_to 'New Post', new_post_path %>
</div>
</div>
</center>

app/views/posts/new.html.erb
<center>

<h1>Submit a New Post</h1>

<%= form_for(@post) do |f| %>
	<div class="field">
		<p>Title</p>
		<%= f.text_field :title%>
	</div>
	<div class="field">
		<p>Comment</p>
		<%= f.text_field :body%>
	<div class="field">
		<%= f.hidden_field :member_id, :value => current_member.id %>
	</div>
	<div class="actions">
		<%=f.submit%>
	</div>
	<div class="error-msg"> 
		<% if @post.errors.any? %> 
		<ul> 
			<% @post.errors.full_messages.each do |msg| %> 
			<li><%= msg %></li> 
 			<% end %> 
 		</ul> 
		<% end %> 
	</div>
<% end %>
</center>

app/views/posts/show.html.erb
<center>
	<div class="content-box">
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @post.stock.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
</div>
</center>