config/routes.rb
Homework1::Application.routes.draw do
  resources :portfolios

  get "pages/index"
  devise_for :members
  resources :investments
  resources :stocks
  resources :members, only: [:show, :index]
  resources :posts
  resources :pages
  
  get "refresh_stocks", to: "stocks#refresh_stocks"
  get "increment_stock/:id/:i_id", to: "stocks#increment_stock", as: "increment_stock"
  get "deincrement_stock/:id/:i_id", to: "stocks#deincrement_stock", as: "deincrement_stock"
  get "delete_stock_investments/:id", to: "investments#delete_stock_investments", as: "delete_stock_investments"
  get "order/:dollar/:decimal", to: "portfolios#order", as: "order"
  
  root 'home#index'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  	<title>Trading Simulation</title>
  	<style type="text/css">
	  	a:link {text-decoration: none;}
	  	a:hover {text-decoration: underline;}
	  	a:active {text-decoration: underline; border-bottom:10px;}
	  	a.sign_in:hover {text-decoration: none;}
	  	a.sign_in:active {text-decoration: none;}
	  </style>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>

<div class= "navbar">
	<ul class= "nav">
		<% if !signed_in? %>
			<li><%=link_to 'Login', new_member_session_path, :class => "nav-link sign_in" %></li>
		<% end %>
		<li><%= link_to 'Annoucements', posts_path, class: "nav-link" %></li>
		<li><%= link_to "Investments", investments_path, class: "nav-link" %></li>
		<li><%= link_to "Stocks", stocks_path, class: "nav-link" %></li>
		<li><%= link_to 'Members', members_path, class: "nav-link" %></li>
	</ul>
</div>

<%= yield %>

<div class= "subbar">
	<ul class= "sub">
		<div id="left-links">
			<li><%= link_to 'Leaderboard', pages_path, class: "sub-link" %></li>
		</div>
		<div id="right-links">
			<li><%= link_to 'Home', root_path, class: "sub-link" %></li>
			<% if signed_in? %>
				<li><%= link_to 'Logout', destroy_member_session_path, :method => :delete, :class => "sub-link" %></li>
			<% end %>
		</div>
	</ul>
</div>
</body>
</html>